TWITTER_BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAEJv7wEAAAAAi%2FeSfl1bucKDr%2BQnkogK2ep58hU%3D3Y68Fv8QjdgVI2ZJAtyfelRioGW1zWtx97fnmf5jsamSEbFqth"
ANTHROPIC_API_KEY = "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"

AWS_ACCESS_KEY_ID     = "AKIA6MYNKSLTM2N3CA6Z"
AWS_SECRET_ACCESS_KEY = "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"
AWS_SES_REGION        = "us-east-1"
EMAIL_FROM            = "streamlit_otp@segaamerica.com"

# Cookie signing
COOKIE_SIGNING_KEY = "097f22301f96c93b553479cd775ed9d0b0af688a56b6f2e4916212e71cd87173"